// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_content_delivery_bucket": "llreactskeleton-20181202194234--hostingbucket",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "http://llreactskeleton-20181202194234--hostingbucket.s3-website-us-west-2.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-west-2:f3521e33-428b-4a7c-8528-deed1849ae52",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_liyiw66yD",
    "aws_user_pools_web_client_id": "vbhh31npj32t2rhmtqks8m26r",
    "aws_mobile_analytics_app_id": "0d0fdf730a634fe2aef649987768e3c3",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_user_files_s3_bucket": "llreactskeletone8b1afd5f67a4b008e0fece78814e309",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
